# Generated by Django 5.2.4 on 2025-07-31 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_exampleopinion_statement_example_opinions"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyStatementMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_stance",
                    models.CharField(
                        choices=[
                            ("strongly_agree", "Strongly Agree"),
                            ("agree", "Agree"),
                            ("neutral", "Neutral"),
                            ("disagree", "Disagree"),
                            ("strongly_disagree", "Strongly Disagree"),
                        ],
                        help_text="Party's stance on this statement",
                        max_length=20,
                    ),
                ),
                (
                    "party_explanation",
                    models.TextField(help_text="Party's explanation of their position"),
                ),
                (
                    "match_score",
                    models.FloatField(
                        help_text="Base agreement score between user and party on this statement"
                    ),
                ),
                (
                    "confidence_weighted_score",
                    models.FloatField(
                        help_text="Match score weighted by user's confidence"
                    ),
                ),
                (
                    "importance_weighted_score",
                    models.FloatField(
                        help_text="Match score weighted by user's importance rating"
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(
                        help_text="Final weighted score (confidence + importance)"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.politicalparty",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_matches",
                        to="profiles.userprofile",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.statement",
                    ),
                ),
                (
                    "user_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_matches",
                        to="profiles.userresponse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Statement Match",
                "verbose_name_plural": "Party Statement Matches",
                "ordering": ["-final_score"],
                "unique_together": {("profile", "statement", "party")},
            },
        ),
    ]
