# Generated by Django 5.2.4 on 2025-07-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_partystatementmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agree", "Agree"),
                    ("neutral", "Neutral"),
                    ("disagree", "Disagree"),
                ],
                help_text="Label for the user's opinion (optional)",
                max_length=20,
                null=True,
            ),
        ),
    ]
