# Generated by Django 5.2.4 on 2025-08-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_userresponse_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="Confidence score for the classified label (0.0 - 1.0)",
                null=True,
            ),
        ),
    ]
