# Generated by Django 5.2.4 on 2025-08-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_userresponse_confidence_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="classified_label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agree", "Agree"),
                    ("neutral", "Neutral"),
                    ("disagree", "Disagree"),
                ],
                help_text="Original label set by the classifier",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="label_set_by",
            field=models.CharField(
                blank=True,
                choices=[("user", "User"), ("AI", "AI Classified")],
                help_text="Who set the label (e.g. 'user', 'AI')",
                max_length=50,
                null=True,
            ),
        ),
    ]
