# Generated by Django 5.2.4 on 2025-08-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_userresponse_classified_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partymatch",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="AI-generated explanation of the match (cached)",
                null=True,
            ),
        ),
    ]
