# Generated by Django 5.2.4 on 2025-07-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parliamentaryseats",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("mauricedehond", "Maurice de Hond"), ("other", "Overig")],
                help_text="Bron van deze zetelstand",
                max_length=25,
                null=True,
            ),
        ),
    ]
