# Generated by Django 5.2.4 on 2025-07-31 08:33

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_parliamentaryseats_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Voorbeeld mening over een stelling"),
                ),
                (
                    "left_wing",
                    models.BooleanField(
                        default=False, help_text="Is deze mening links georiënteerd?"
                    ),
                ),
                (
                    "right_wing",
                    models.BooleanField(
                        default=False, help_text="Is deze mening rechts georiënteerd?"
                    ),
                ),
                (
                    "progressive",
                    models.BooleanField(
                        default=False,
                        help_text="Is deze mening progressief georiënteerd?",
                    ),
                ),
                (
                    "conservative",
                    models.BooleanField(
                        default=False,
                        help_text="Is deze mening conservatief georiënteerd?",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stemwijzer", "StemWijzer"),
                            ("kieskompas", "KiesKompas"),
                            ("AI", "AI Generated"),
                            ("other", "Overig"),
                        ],
                        help_text="Bron van deze voorbeeld mening",
                        max_length=25,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="statement",
            name="example_opinions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Voorbeeld meningen over deze stelling",
                related_name="statements",
                to="content.exampleopinion",
            ),
        ),
    ]
