# Generated by Django 5.2.4 on 2025-07-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_exampleopinion_statement_example_opinions"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpinionComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comparison_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash van statement, gebruikersmening en geselecteerde partijen",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "statement_id",
                    models.CharField(help_text="ID van de statement", max_length=100),
                ),
                (
                    "user_opinion",
                    models.CharField(
                        help_text="Gebruikersmening (strongly_agree, agree, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "party_ids",
                    models.JSONField(help_text="Lijst van geselecteerde partij IDs"),
                ),
                (
                    "comparison_result",
                    models.TextField(
                        help_text="AI-gegenereerde vergelijking in markdown format"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Wanneer de vergelijking werd aangemaakt",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="gpt-4o",
                        help_text="Welk AI model werd gebruikt",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opinion Comparison",
                "verbose_name_plural": "Opinion Comparisons",
                "ordering": ["-created_at"],
            },
        ),
    ]
