# Generated by Django 5.2.4 on 2025-07-31 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_opinioncomparison"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opinioncomparison",
            name="party_ids",
        ),
        migrations.RemoveField(
            model_name="opinioncomparison",
            name="user_opinion",
        ),
        migrations.AddField(
            model_name="opinioncomparison",
            name="parties",
            field=models.ManyToManyField(
                help_text="Geselecteerde partijen voor de vergelijking",
                related_name="comparisons",
                to="content.politicalparty",
            ),
        ),
        migrations.AddField(
            model_name="opinioncomparison",
            name="user_response",
            field=models.ForeignKey(
                default=0,
                help_text="Gebruikers mening die vergeleken wordt",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons",
                to="content.exampleopinion",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="opinioncomparison",
            name="model_used",
            field=models.CharField(
                default="gpt-4o",
                help_text="Welk AI model werd gebruikt",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="opinioncomparison",
            name="statement_id",
            field=models.ForeignKey(
                help_text="De stelling waar deze vergelijking betrekking op heeft",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons",
                to="content.statement",
            ),
        ),
    ]
