# Generated by Django 5.2.4 on 2025-07-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_remove_opinioncomparison_party_ids_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opinioncomparison",
            name="parties",
        ),
        migrations.RemoveField(
            model_name="opinioncomparison",
            name="statement_id",
        ),
        migrations.RemoveField(
            model_name="opinioncomparison",
            name="user_response",
        ),
    ]
