# Generated by Django 5.2.4 on 2025-07-31 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_remove_opinioncomparison_parties_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliticalDimensions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "economic",
                    models.FloatField(
                        default=0.0,
                        help_text="Economische score: -1 (links) tot +1 (rechts)",
                    ),
                ),
                (
                    "social",
                    models.FloatField(
                        default=0.0,
                        help_text="Sociale score: -1 (progressief) tot +1 (conservatief)",
                    ),
                ),
                (
                    "environmental",
                    models.FloatField(
                        default=0.0, help_text="Milieu score: -1 (groen) tot +1 (bruin)"
                    ),
                ),
                (
                    "immigration",
                    models.FloatField(
                        default=0.0,
                        help_text="Immigratie score: -1 (open) tot +1 (gesloten)",
                    ),
                ),
                (
                    "europe",
                    models.FloatField(
                        default=0.0,
                        help_text="Europa score: -1 (pro-EU) tot +1 (anti-EU)",
                    ),
                ),
                (
                    "authority",
                    models.FloatField(
                        default=0.0,
                        help_text="Autoriteit score: -1 (libertair) tot +1 (autoritaire)",
                    ),
                ),
                (
                    "institutionality",
                    models.FloatField(
                        default=0.0,
                        help_text="Institutionaliteit score: -1 (institutioneel) tot +1 (anti-elite/populistisch)",
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="Onderbouwing of bewijs voor deze dimensies",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="exampleopinion",
            name="dimensions",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="example_opinion",
                to="content.politicaldimensions",
            ),
        ),
        migrations.AddField(
            model_name="programfragment",
            name="dimensions",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_fragment",
                to="content.politicaldimensions",
            ),
        ),
        migrations.AddField(
            model_name="statementposition",
            name="dimensions",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statement_position",
                to="content.politicaldimensions",
            ),
        ),
    ]
