# Generated by Django 5.2.4 on 2025-07-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_politicaldimensions_exampleopinion_dimensions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="politicaldimensions",
            name="confidence",
            field=models.FloatField(
                default=0.0,
                help_text="Vertrouwen in de dimensies, van 0.0 (laag) tot 1.0 (hoog)",
            ),
        ),
    ]
