# Generated by Django 5.2.4 on 2025-07-31 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_politicaldimensions_confidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ranking",
                    models.IntegerField(
                        default=0,
                        help_text="Importance ranking of this position from the party's view",
                    ),
                ),
                (
                    "short",
                    models.TextField(
                        blank=True,
                        help_text="Short statement of the position",
                        null=True,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of the position",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_positions",
                        to="content.politicalparty",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_positions",
                        to="content.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Position",
                "verbose_name_plural": "Party Positions",
                "unique_together": {("party", "topic", "ranking")},
            },
        ),
    ]
