# Generated by Django 5.2.4 on 2025-08-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_partyposition"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyPositionSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0,
                        help_text="How relevant this source is to the position (0-1)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="content.partyposition",
                    ),
                ),
                (
                    "program_fragment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to a program fragment used as source",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.programfragment",
                    ),
                ),
                (
                    "statement_position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to a statement position used as source",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.statementposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Position Source",
                "verbose_name_plural": "Party Position Sources",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("program_fragment__isnull", True),
                                ("statement_position__isnull", False),
                            ),
                            models.Q(
                                ("program_fragment__isnull", False),
                                ("statement_position__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="exactly_one_source_type",
                    )
                ],
            },
        ),
    ]
