# Generated by Django 5.2.4 on 2025-08-04 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_add_party_position_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_background",
                    models.TextField(help_text="Achtergrond van het onderwerp"),
                ),
                (
                    "current_state",
                    models.TextField(help_text="Huidige situatie en stand van zaken"),
                ),
                (
                    "possible_solutions",
                    models.TextField(
                        help_text="Mogelijke oplossingen en beleidskeuzes"
                    ),
                ),
                (
                    "different_perspectives",
                    models.TextField(
                        help_text="Verschillende perspectieven en standpunten"
                    ),
                ),
                (
                    "why_relevant",
                    models.TextField(help_text="Waarom dit onderwerp relevant is"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statement",
                    models.OneToOneField(
                        help_text="De stelling waarvoor deze context is gegenereerd",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context",
                        to="content.statement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statement Context",
                "verbose_name_plural": "Statement Contexts",
            },
        ),
    ]
