# Generated by Django 5.2.4 on 2025-07-31 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(help_text="De vraag van de gebruiker")),
                ("answer", models.TextField(help_text="Het AI-gegenereerde antwoord")),
                (
                    "model_used",
                    models.CharField(
                        default="gpt-3.5-turbo",
                        help_text="AI model gebruikt voor antwoord",
                        max_length=100,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Verwerkingstijd in milliseconden",
                        null=True,
                    ),
                ),
                (
                    "helpful_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Gebruiker rating 1-5",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parties",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Lijst van politieke partijen voor context",
                        to="content.politicalparty",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Het hoofd-onderwerp van de vraag, indien van toepassing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.topic",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0, help_text="Relevantie score van 0.0 tot 1.0"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Volgorde van bronnen in antwoord"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "program_fragment",
                    models.ForeignKey(
                        help_text="Het programma fragment dat als bron is gebruikt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.programfragment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Source",
                "verbose_name_plural": "Message Sources",
                "ordering": ["message", "order"],
                "unique_together": {("message", "program_fragment")},
            },
        ),
    ]
